# Generated by Django 5.0.14 on 2026-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmMaster',
            fields=[
                ('FirmID', models.IntegerField(db_column='FirmID', primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, db_column='FName', max_length=50, null=True)),
                ('Under', models.IntegerField(db_column='Under', default=0)),
                ('SubHead', models.CharField(blank=True, db_column='SubHead', max_length=50, null=True)),
                ('FStatus', models.IntegerField(blank=True, db_column='FStatus', default=1, null=True)),
                ('Phone', models.CharField(blank=True, db_column='Phone', max_length=10, null=True)),
                ('Address1', models.CharField(blank=True, db_column='Address1', max_length=20, null=True)),
                ('Address2', models.CharField(blank=True, db_column='Address2', max_length=20, null=True)),
                ('Address3', models.CharField(blank=True, db_column='Address3', max_length=20, null=True)),
            ],
            options={
                'db_table': 'FirmMaster',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False},
        ),
    ]
