# common/models/report_details.py
"""
ReportDetails model — column definitions + table creator for BaseCRUD.

Usage in views:
    from common.models.report_details import ensure_report_details_table, REPORT_DETAILS_FIELD_MAP
    from core.crud import BaseCRUD

    crud = BaseCRUD(
        table         = 'ReportDetails',
        pk_col        = 'SlNo',
        field_map     = REPORT_DETAILS_FIELD_MAP,
        db_alias      = get_customer_db(),
        table_creator = ensure_report_details_table,
    )
"""

import logging
from django.db import connections

logger = logging.getLogger(__name__)

# ── Field map (unified BaseCRUD format) ───────────────────────────────────────
# DB column name → (form field name, type token)
# SlNo is excluded — it is a serial PK auto-generated by the DB sequence.

REPORT_DETAILS_FIELD_MAP = {
    'ReportName': ('report_name', 'str'),
    'MRName'    : ('mr_name',     'str'),
    'Section'   : ('section',     'str'),
    'FName'     : ('fname',       'str'),
    'UFName'    : ('ufname',      'str'),
    'Width'     : ('width',       'float'),
    'Index'     : ('index',       'float'),
    'Alignment' : ('alignment',   'float'),
    'Show'      : ('show',        'int'),
    'Heder'     : ('heder',       'int'),
    'Break'     : ('break_col',   'int'),   # 'break' is a Python keyword
    'UIndex'    : ('uindex',      'float'),
    'UWidth'    : ('uwidth',      'float'),
    'MReport'   : ('mreport',     'int'),
    'DField'    : ('dfield',      'int'),
    'Font'      : ('font',        'int'),
    'FieldType' : ('field_type',  'int'),
    'FormatText': ('format_text', 'str'),
    'FontName'  : ('font_name',   'str'),
    'SYS_ITEM'  : ('sys_item',    'int'),
    'Color'     : ('color',       'str'),
    'FKTable'   : ('fk_table',    'str'),
    'FKIDField' : ('fk_id_field', 'str'),
    'FKField'   : ('fk_field',    'str'),
}


_ENSURED_REPORT_DETAILS_TABLES = set()


def ensure_report_details_table(db_alias: str, force: bool = False) -> bool:
    """
    Create ReportDetails if it doesn't exist, then guarantee that SlNo
    has a sequence-backed DEFAULT (handles tables created without serial).
    Cached in memory so it executes at most once per process.

    Called automatically by BaseCRUD on every save/get/list via table_creator.
    Returns True if the table was freshly created, False if it already existed.
    """
    if not force and db_alias in _ENSURED_REPORT_DETAILS_TABLES:
        return False

    try:
        conn = connections[db_alias]
        with conn.cursor() as cur:

            # ── 1. Check if table already exists ─────────────────────────────
            cur.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE  table_schema = 'public'
                      AND  table_name   = 'ReportDetails'
                )
            """)
            already_exists = cur.fetchone()[0]

            # ── 2. Create table (serial = int + sequence + DEFAULT nextval) ──
            cur.execute("""
                CREATE TABLE IF NOT EXISTS "ReportDetails" (
                    "SlNo"       serial PRIMARY KEY,
                    "ReportName" varchar(50)  DEFAULT '',
                    "MRName"     varchar(50)  DEFAULT '',
                    "Section"    varchar(50)  DEFAULT '',
                    "FName"      varchar(150) DEFAULT '',
                    "UFName"     varchar(50)  DEFAULT '',
                    "Width"      numeric      DEFAULT 0,
                    "Index"      numeric      DEFAULT 0,
                    "Alignment"  numeric      DEFAULT 0,
                    "Show"       smallint     DEFAULT 1,
                    "Heder"      smallint     DEFAULT 0,
                    "Break"      smallint     DEFAULT 0,
                    "UIndex"     numeric      DEFAULT 0,
                    "UWidth"     numeric      DEFAULT 0,
                    "MReport"    smallint     DEFAULT 0,
                    "DField"     smallint     DEFAULT 0,
                    "Font"       smallint     DEFAULT 0,
                    "FieldType"  smallint     DEFAULT 1,
                    "FormatText" varchar(50)  DEFAULT '',
                    "FontName"   char(45)     DEFAULT '',
                    "SYS_ITEM"   smallint     DEFAULT 0,
                    "Color"      char(20)     DEFAULT '',
                     "FKTable"    varchar(100) DEFAULT '',
                     "FKField"    varchar(100) DEFAULT ''
                )
            """)

            # ── 3. Lookup index ───────────────────────────────────────────────
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_reportdetails_mrname_reportname
                ON "ReportDetails" ("MRName", "ReportName")
                        
            """)
            for col, coldef in [
                ('"FKTable"',   'varchar(100) DEFAULT \'\''),
                ('"FKIDField"', 'varchar(100) DEFAULT \'\''),
                ('"FKField"',   'varchar(100) DEFAULT \'\''),
            ]:
                cur.execute(f"""
                    ALTER TABLE "ReportDetails"
                    ADD COLUMN IF NOT EXISTS {col} {coldef}
                """)

            # ── 4. Repair SlNo sequence if table pre-existed without one ─────
            #      This is idempotent — safe every call, cheap after first run.
            cur.execute("""
                DO $$
                DECLARE
                    has_default BOOLEAN;
                    seq_name    TEXT := 'reportdetails_slno_seq';
                BEGIN
                    SELECT column_default IS NOT NULL
                    INTO   has_default
                    FROM   information_schema.columns
                    WHERE  table_name  = 'ReportDetails'
                      AND  column_name = 'SlNo';

                    IF NOT has_default THEN
                        EXECUTE format(
                            'CREATE SEQUENCE IF NOT EXISTS %I
                             START WITH 1 INCREMENT BY 1
                             NO MINVALUE NO MAXVALUE CACHE 1',
                            seq_name
                        );
                        -- Advance past existing max to avoid PK collisions
                        EXECUTE format(
                            'SELECT setval(%L,
                                COALESCE((SELECT MAX("SlNo") FROM "ReportDetails"), 0) + 1,
                                false)',
                            seq_name
                        );
                        EXECUTE format(
                            'ALTER TABLE "ReportDetails"
                             ALTER COLUMN "SlNo" SET DEFAULT nextval(%L)',
                            seq_name
                        );
                        EXECUTE format(
                            'ALTER SEQUENCE %I OWNED BY "ReportDetails"."SlNo"',
                            seq_name
                        );
                    END IF;
                END
                $$;
            """)

        _ENSURED_REPORT_DETAILS_TABLES.add(db_alias)
        return not already_exists

    except Exception as e:
        logger.error('[ensure_report_details_table] %s – %s', db_alias, e, exc_info=True)
        return False